import fs from 'fs';
import path from 'path';

const SKIP_DIRS = new Set([
  '.git',
  'node_modules',
  '.harness',
  '.harness-index',
  'dist',
  'build',
  'coverage',
  '.turbo',
  'target',
  '__pycache__',
  '.venv',
  'venv',
]);

const MANIFEST_NAMES = [
  'package.json',
  'pom.xml',
  'pyproject.toml',
  'go.mod',
  'Cargo.toml',
];

const DEFAULT_MAX_FILES = 200;
const DEFAULT_MAX_BYTES = 8000;
const README_LINES = 80;
const TREE_DEPTH = 4;

function estimateTokens(text) {
  return Math.ceil(Buffer.byteLength(text, 'utf8') / 4);
}

function shouldSkipDir(name) {
  return SKIP_DIRS.has(name) || name.startsWith('.');
}

function buildTree(dir, prefix, depth, maxFiles, state) {
  if (depth > TREE_DEPTH || state.count >= maxFiles) return;
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const ent of entries) {
    if (state.count >= maxFiles) break;
    if (ent.isDirectory()) {
      if (shouldSkipDir(ent.name)) continue;
      state.lines.push(`${prefix}${ent.name}/`);
      state.count++;
      buildTree(path.join(dir, ent.name), `${prefix}  `, depth + 1, maxFiles, state);
    } else {
      state.lines.push(`${prefix}${ent.name}`);
      state.count++;
    }
  }
}

function readJsonManifest(workspace, name) {
  const full = path.join(workspace, name);
  if (!fs.existsSync(full)) return null;
  try {
    if (name === 'package.json') {
      const j = JSON.parse(fs.readFileSync(full, 'utf8'));
      return {
        type: 'node',
        name: j.name,
        version: j.version,
        scripts: j.scripts || {},
      };
    }
    return { type: name, path: name };
  } catch {
    return null;
  }
}

function manifestTable(workspace) {
  const rows = [];
  for (const name of MANIFEST_NAMES) {
    const m = readJsonManifest(workspace, name);
    if (!m) continue;
    if (m.type === 'node') {
      rows.push(`| ${name} | ${m.name || '—'} | test: \`${m.scripts?.test || '—'}\` |`);
    } else {
      rows.push(`| ${name} | present | — |`);
    }
  }
  if (!rows.length) return '_No standard manifests at repo root._';
  return ['| Manifest | Project | Tests |', '|----------|---------|-------|', ...rows].join('\n');
}

function readmeExcerpt(workspace) {
  for (const name of ['README.md', 'Readme.md', 'readme.md']) {
    const full = path.join(workspace, name);
    if (!fs.existsSync(full)) continue;
    const lines = fs.readFileSync(full, 'utf8').split('\n').slice(0, README_LINES);
    return { name, text: lines.join('\n') };
  }
  return null;
}

function planTitles(workspace) {
  const plansDir = path.join(workspace, 'docs', 'plans');
  if (!fs.existsSync(plansDir)) return [];
  const titles = [];
  for (const f of fs.readdirSync(plansDir)) {
    if (!f.endsWith('.md') || f.startsWith('_')) continue;
    const text = fs.readFileSync(path.join(plansDir, f), 'utf8');
    const m = text.match(/^title:\s*["']?([^"'\n]+)/m);
    const status = text.match(/^status:\s*(\S+)/m);
    titles.push(`- \`${f}\` — ${m?.[1] || f} (${status?.[1] || 'unknown'})`);
    if (titles.length >= 20) break;
  }
  return titles;
}

function entryPointHints(workspace) {
  const hints = [];
  const candidates = [
    'src/index.ts',
    'src/index.js',
    'src/main.ts',
    'src/main.py',
    'main.py',
    'app.py',
    'src/Application.java',
    'cmd/main.go',
  ];
  for (const rel of candidates) {
    if (fs.existsSync(path.join(workspace, rel))) hints.push(rel);
  }
  return hints;
}

/**
 * Deterministic codebase map (no LLM).
 */
export function runSnapshot({ workspace, flags }) {
  const maxFiles = flags.snapshotMaxFiles || DEFAULT_MAX_FILES;
  const outRel =
    flags.snapshotOut ||
    (flags.snapshotCommit ? 'docs/codebase-map.md' : '.harness/codebase-map.md');
  const outFull = path.join(workspace, outRel);

  const treeState = { lines: [], count: 0 };
  buildTree(workspace, '', 0, maxFiles, treeState);

  const readme = readmeExcerpt(workspace);
  const plans = planTitles(workspace);
  const entries = entryPointHints(workspace);
  const agentCtx = path.join(workspace, 'docs', 'agent-context.md');
  const generated = new Date().toISOString().slice(0, 10);

  const sections = [
    '# Codebase Map',
    '',
    `> Generated by \`harness snapshot\` on ${generated}. No LLM. Refresh when structure changes.`,
    '',
    '## Stack (manifests)',
    manifestTable(workspace),
    '',
    '## Directory tree (depth-limited)',
    '```',
    treeState.lines.join('\n') || '(empty)',
    '```',
    '',
    '## Entry points (heuristic)',
    entries.length ? entries.map((e) => `- \`${e}\``).join('\n') : '- _(none detected)_',
    '',
    '## README excerpt',
    readme ? `From \`${readme.name}\`:\n\n${readme.text}` : '_No README at repo root._',
    '',
    '## Active plans (titles only)',
    plans.length ? plans.join('\n') : '- _(no docs/plans/*.md)_',
  ];

  if (fs.existsSync(agentCtx)) {
    sections.push('', '## Agent context', `- See \`docs/agent-context.md\` for repo conventions.`);
  }

  sections.push(
    '',
    '## Usage',
    '- VS Code: prefer workspace semantic search when index is ready.',
    '- Run `harness snapshot` after major restructure or when map is stale (`harness doctor`).',
    '',
    `## Token estimate`,
    ''
  );

  let body = sections.join('\n');
  const tokens = estimateTokens(body);
  body += `~${tokens} tokens (byteLength/4 approximation).\n`;

  const result = {
    out: outRel.replace(/\\/g, '/'),
    bytes: Buffer.byteLength(body, 'utf8'),
    tokenEstimate: tokens,
    treeEntries: treeState.count,
  };

  if (!flags.dryRun) {
    fs.mkdirSync(path.dirname(outFull), { recursive: true });
    fs.writeFileSync(outFull, body, 'utf8');
  }

  return result;
}
